version: "2"

services:
  eosiod:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/start_eosiod.sh
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ${HOME}/.eos/eosiod:/opt/eosio/bin/data-dir
      - ./config.ini:/opt/eosio/bin/data-dir/config.ini

  walletd:
    image: eosio/eos
    command: /opt/eosio/bin/eosiowd
    links:
      - eosiod
    volumes:
      - ${HOME}/.eos/walletd:/opt/eosio/bin/data-dir
